#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'chiefHopper' function below.
#
# The function is expected to return an INTEGER.
# The function accepts INTEGER_ARRAY arr as parameter.
#
def chiefHopper(arr):
    energy = 0  # Start with 0 energy at the last building
    for height in reversed(arr):  # Traverse the buildings from last to first
        # The bot needs energy to jump up, but also gets energy if it's lower than the building
        energy = (energy + height + 1) // 2  # Minimum energy needed after this building
    return energy

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    n = int(input().strip())

    arr = list(map(int, input().rstrip().split()))

    result = chiefHopper(arr)

    fptr.write(str(result) + '\n')

    fptr.close()
