#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'encryption' function below.
#
# The function is expected to return a STRING.
# The function accepts STRING s as parameter.
#

def encryption(s):
    s = s.replace(" ", "")
    L = len(s)

    rows = math.floor(math.sqrt(L))
    cols = math.ceil(math.sqrt(L))

    if rows * cols < L:
        rows += 1

    encrypted_message = []
    for c in range(cols):
        column_word = []
        for r in range(rows):
            index = r * cols + c
            if index < L:
                column_word.append(s[index])
        encrypted_message.append("".join(column_word))
    
    return " ".join(encrypted_message)

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    s = input()

    result = encryption(s)

    fptr.write(result + '\n')

    fptr.close()
