#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'largestRectangle' function below.
#
# The function is expected to return a LONG_INTEGER.
# The function accepts INTEGER_ARRAY h as parameter.
#

def largestRectangle(heights):
    stack = [] 
    max_area = 0
    heights.append(0) 
    for i, h in enumerate(heights):
        while stack and heights[stack[-1]] > h:
            height=heights[stack.pop()]
            width=i if not stack else i-stack[-1] - 1
            max_area=max(max_area,height*width)
        stack.append(i)
    return max_area

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    n = int(input().strip())

    h = list(map(int, input().rstrip().split()))

    result = largestRectangle(h)

    fptr.write(str(result) + '\n')

    fptr.close()
